apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: visits
          image: farhan899/simple-visits-app
          ports:
            - containerPort: 8080
          env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'  
